honeybot/plugins/username.py

Added username changes

---

honeybot/PLUGINS.conf
honeybot/plugins/quote.py

Add quotes plugin

---

README.md

I formalized the readme a bit. Take a look at it and tell me if you're okay with the changes and if you have any recommendations. I'm still trying to get the program to work on the IRC client right now but I'll be sure to add stuff as soon as I figure out the stack.

Formalizing the readme.md

---

.idea/honeybot.iml
.idea/misc.xml
.idea/workspace.xml
honeybot/PLUGINS.conf
honeybot/plugins/dictionary.py

Added plugin for dictionary to return meaning of a word

Add Dictionary plugin

---

.idea/workspace.xml
honeybot/main.py
honeybot/plugins/dictionary.py

Updated the documentation of dictionary plugin and optimised imports over main file

Updated Dictionary plugin

---

honeybot/PLUGINS.conf

Updated PLUGINS.conf

---

honeybot/PLUGINS.conf
honeybot/plugins/wikipedia.py
honeybot/plugins_info.md

Yay no conflicts with any xml file! On another note, I am 90% sure this will work. I'm just not *entirely* sure how it will handle the multiline string, but after looking as the source code for main and irc.send, it *should* work. This is for Issue #30.

Added in the wikipedia plugin

---

honeybot/PLUGINS.conf
honeybot/plugins/weather.py
honeybot/plugins_info.md

Made the weather plugin. This may not work initially as the API key isn't fully initialized. Done with https://openweathermap.org/api to solve Issue #4

Weather Plugin

---

honeybot/plugins/wikipedia.py
honeybot/plugins_info.md

Added the search feature to the wikipedia plugin and updated the description to refelct it. Issue #50

Added search feature to wikipedia plugin

---

honeybot/pluginInfo.py
honeybot/plugins/bitcoin.py
honeybot/plugins/wikipedia.py
honeybot/plugins_info.md

Updated the plugin info script to output richer mark-down than before. Also added website for the plugins I wrote to show how it would work.

Made the info plugin output nicer markdown

---

.gitignore

I updated the .gitignore to ignore .idea/ so that we can avoid the conflicts with workspace.xml and the such

Added in .idea/

---

README.md

Add uncredited plugins to readme file.
Solves https://github.com/Abdur-rahmaanJ/honeybot/issues/51

Update readme plugin list.

---

README.md

Added Testimonials section to README, and added my personal one.

Testimonials added to README

---

README.md

added project testimonial 

---

honeybot/plugins/age.py

Age plugin that takes in birthday and outputs age. I can modify it to allow for a day/mo/yr with the '/' included if you want.
Completes https://github.com/Abdur-rahmaanJ/honeybot/issues/75

Age plugin

---

honeybot/plugins/fact.py

Fact plugin returns a random fact when '.fact' is entered.
Completes https://github.com/Abdur-rahmaanJ/honeybot/issues/74

Fact plugin

---

.gitignore
workshop/HoneyGUI/CMakeLists.txt
workshop/HoneyGUI/main.cpp

I'm literally just adding the C++ files for the GUI and making it so the bad stuff doesn't get through.

Created enviroment for GUI

---

honeybot/plugins/joins.py
honeybot/settings/STD_PLUGINS.conf

plugin greet everyone who joins the channel

added joins plugins

---

.gitignore
honeybot/plugins/roll.py
honeybot/plugins_info.md

Created roll.py, a new plugin that can roll 1 or more dice.
Also added Visual Studio Code settings folder to ignore, and lastly updated plugins_info.md

Add .roll plugin and also added vscode to .ignore

---

honeybot/plugins/send_message.py
honeybot/settings/STD_PLUGINS.conf

Sends message to another channel or to user in another channel. Tested on IRC and is working.
Completes https://github.com/Abdur-rahmaanJ/honeybot/issues/78

Send message plugin

---

honeybot/plugins/send_message.py

Fix indent issue.

---

honeybot/plugins/date.py
honeybot/settings/STD_PLUGINS.conf

made a date plugin. Month(name) day, year

added date plugin

---

README.md
hangman.txt

Add my testimonial to Readme and remove hangman.txt.

Testimonial

---

honeybot/main.py

#8
Changed all print statements in main.py to pythons logging module.
This change will keep a cleaner output to console in future testing.
Module also allows allows logging to any other location like files or even the creation of custom locations.
https://docs.python.org/3/howto/logging.html

Change Print to Logging

---

.gitignore
honeybot/plugins/weather.py

Changed weather.py to report celsius

---

README.md
honeybot/plugins/riddle.py

I have added a riddle plugin which is like the joke and trivia plugin in structure. I have added the answers in case anyone wants to extend this plugin to allow guesses. I have also added the flag of the UK to the contributing countries list.

create riddle plugin

---

workshop/HoneyGUI/CMakeLists.txt
workshop/HoneyGUI/guiBase.cpp
workshop/HoneyGUI/guiBase.h
workshop/HoneyGUI/main.cpp
workshop/HoneyGUI/optionDisplay.cpp
workshop/HoneyGUI/optionDisplay.h
workshop/HoneyGUI/optionList.cpp
workshop/HoneyGUI/optionList.h

Created the base for the HoneyGUI project. This is in reference to Issue #77.

The base for the HoneyGUI

---

README.md

Nothing special, just updated the readme so that all plugins are mentioned in the list

Update plugins readme

---

README.md
honeybot/plugins/roll.py
honeybot/test_plugin_script.py

Created a plugin tester script to test simple plugins.

Added new Plugin Tester file and updated Roll Plugin

---

README.md
honeybot/plugins/horoscope.py

A plugin that gets your daily horoscope for your starsign. 
I have updated the readme as well to include the plugin

Horoscope Plugin

---

honeybot/plugins_info.md

I updated the plugin info markdown file.

Update plugin info

---

workshop/HoneyGUI/configDisplay.cpp
workshop/HoneyGUI/pluginDisplay.cpp
workshop/HoneyGUI/pluginDisplay.h

Removed the calls to STD_PLUGINS.conf and cleaned up the temp.txt

Added cleanup

---

honeybot/main.py
honeybot/plugins/roman_numeral.py
honeybot/test_plugin_script.py

Added roman numeral converter

---

README.md

This commit adds my experience with this project in the readme testimonials.

Add testimonial

---

honeybot/plugins/abbreviation.py

I want to resolve #158 with this PR.
I looked at Urban dictionary as requested in the issue. However, I did not find any pattern with which I can find the abbreviation or extract its expanded form. So, I have added a dictionary for looking up of requested abbreviation. The dictionary contains the most popular abbreviations mentioned in Urban dictionary. Let me know if this is okay or if you have any suggestions.

added dictionary for abbreviations

---

honeybot/plugins/joke.py

Added a joke to the joke pluggin, this is my first ever PR.

added a joke

---

honeybot/main.py

This is how I would like to implement SASL auth and communication for the bot, with a subclass of class Bot_core. 
A pass is in place while I build the functionality. I feel like requesting a pull of simple commits to my forked branch a little at a time will help ease the transition. 
Thoughts?

SASL subclass prototype
